export const topPlaces = [
  { city: "Sydney", country: "Australia", activityName: "Sydney Opera House" },
  { city: "Sydney", country: "Australia", activityName: "Sydney Harbour Bridge Climb" },
  { city: "Sydney", country: "Australia", activityName: "Bondi Beach" },
  { city: "Sydney", country: "Australia", activityName: "Taronga Zoo Sydney" },
  { city: "Sydney", country: "Australia", activityName: "Royal Botanic Garden" },
  { city: "Sydney", country: "Australia", activityName: "The Rocks" },
  { city: "Sydney", country: "Australia", activityName: "Circular Quay" },
  { city: "Sydney", country: "Australia", activityName: "Manly Beach" },
  { city: "Sydney", country: "Australia", activityName: "Darling Harbour" },
  { city: "Sydney", country: "Australia", activityName: "Art Gallery of New South Wales" },
  { city: "Sydney", country: "Australia", activityName: "Luna Park" },
  { city: "Sydney", country: "Australia", activityName: "Museum of Contemporary Art" },
  { city: "Sydney", country: "Australia", activityName: "Hyde Park" },
  { city: "Sydney", country: "Australia", activityName: "Watsons Bay" },
  { city: "Sydney", country: "Australia", activityName: "Coogee to Bondi Coastal Walk" },
  { city: "Sydney", country: "Australia", activityName: "Sydney Tower Eye" },
  { city: "Sydney", country: "Australia", activityName: "Centennial Parklands" },
  { city: "Sydney", country: "Australia", activityName: "Queen Victoria Building (QVB)" },
  { city: "Sydney", country: "Australia", activityName: "Raging Waters Sydney" },
];
