-- NOTE:
-- This migration used to contain a project-specific `pg_cron` schedule with a placeholder URL.
-- Keeping it as a NO-OP prevents accidentally scheduling a broken job on new environments.
--
-- If you want to enable the cleanup job, create a new migration with:
-- - The correct Edge Function URL for your Supabase project
-- - Any required extensions (e.g. `pg_cron`, `pg_net`) enabled via the dashboard
